# Travis configuration

language: python

dist: trusty
sudo: false

matrix:
    include:
        - os: linux
          python: 2.7
          env:
            - CXX=clang++ CC=clang

        - os: linux
          python: 2.7
          env:
            - CXX=g++ CC=gcc

        - os: linux
          python: 3.3
          env:
            - CXX=clang++ CC=clang

        - os: linux
          python: 3.4
          env:
            - CXX=clang++ CC=clang

        - os: linux
          python: 3.5
          env:
            - CXX=clang++ CC=clang

        - os: linux
          python: 3.6
          env:
            - CXX=clang++ CC=clang

        - os: linux
          python: 3.6
          env:
            - CXX=g++ CC=gcc

        - os: osx
          language: generic

addons:
    apt:
        packages:
            - pandoc
            - texlive-base

before_script:
  # Install system requirements for OSX (pylibpcap, libdnet and pandoc)
  - if [ ${TRAVIS_OS_NAME} == "osx" ]; then
      mkdir -p /Users/travis/Library/Python/2.7/lib/python/site-packages;
      echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/travis/Library/Python/2.7/lib/python/site-packages/homebrew.pth;
      brew update;
      brew install --with-python libdnet;
      brew install https://raw.githubusercontent.com/secdev/scapy/master/.travis/pylibpcap.rb;
      brew install pandoc;
    fi
  # Determine the pip vesion to use
  - PIP=`which pip || (python --version 2>&1 | grep -q 'Python 2' && which pip2) || (python --version 2>&1 | grep -q 'Python 3' && which pip3)`

install:
  - $PIP install .
  - $PIP install six
  - $PIP install -r requirements-docs.txt
  - $PIP install -r requirements-optional.txt

script:
  - python setup.py test
  - python setup.py doc

before_deploy:
  # Build a source and wheel artifact
  - python setup.py sdist
  - python setup.py bdist_wheel

deploy:
    provider: releases
    api_key:
        secure: jph0ZzpFytrPyZKm71s7LwaXvQ2QkGMM1DgwiBu4p9E99vAKvpNdVOXvyp4BmMp7PEksUKtPYpyGWIQCoTY7ffJUf72VbXLxLfsNqpGMP62UteVt5ssleYvpzVqfTt26gqGvsMZB2EhP9zpH3AgYaGuJIB1L0/CM+5Ilf3u2j4I=
    file:
        - "dist/*.whl"
        - "dist/*.tar.gz"
    file_glob: true
    skip_cleanup: true
    on:
        tags: true
        repo: CoreSecurity/pysap
